In [8]:
import pandas as pd

df = pd.read_csv("crime_data.csv")

In [6]:
df.head()

,DR_NO,Date reported,Time reported,Date occurred,Time occurred,AREA,AREA NAME,Report District No,Crime Code,Crime Code Description,Victim Age,Victim Gender,Victim Descent,Premises Code,Premises Desc,Weapon Used Code,Weapon Used Description,Status,Status Description,Location
0,10304468,01-08-2020,8:42:40 AM,01-08-2020,7:01:35 PM,3,Southwest,377,624,Battery - Simple Assault,36,F,B,501.0,Single Family Dwelling,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,1100 W 39Th Pl
1,190101086,01-02-2020,3:08:56 PM,01-01-2020,9:07:23 AM,1,Central,163,624,Battery - Simple Assault,25,M,H,102.0,Sidewalk,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,700 S Hill St
2,200110444,04-14-2020,2:53:31 PM,02-13-2020,7:53:55 AM,1,Central,155,845,Sex Offender Registrant Out Of Compliance,0,X,X,726.0,Police Facility,NaN,NaN,AA,Adult Arrest,200 E 6Th St
3,191501505,01-01-2020,2:27:04 PM,01-01-2020,10:46:48 AM,15,N Hollywood,1543,745,Vandalism - Misdeameanor ($399 Or Under),76,F,W,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",NaN,NaN,IC,Invest Cont,5400 Corteen Pl
4,191921269,01-01-2020,8:45:43 PM,01-01-2020,11:15:31 PM,19,Mission,1998,740,"Vandalism - Felony ($400 & Over, All Church Va...",31,X,X,409.0,Beauty Supply Store,NaN,NaN,IC,Invest Cont,14400 Titus St

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 752911 entries, 0 to 752910
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   DR_NO                    752911 non-null  int64
 1   Date reported            752911 non-null  str
 2   Time reported            752911 non-null  str
 3   Date occurred            752911 non-null  str
 4   Time occurred            752911 non-null  str
 5   AREA                     752911 non-null  int64
 6   AREA NAME                752911 non-null  str
 7   Report District No       752911 non-null  int64
 8   Crime Code               752911 non-null  int64
 9   Crime Code  Description  752911 non-null  str
 10  Victim Age               752911 non-null  int64
 11  Victim Gender            654681 non-null  str
 12  Victim Descent           654675 non-null  str
 13  Premises Code            752902 non-null  float64
 14  Premises Desc            752476 non-null  str
 15  Weapon Used Code         261472 non-null  float64
 16  Weapon Used Description  261472 non-null  str
 17  Status                   752911 non-null  str
 18  Status Description       752911 non-null  str
 19  Location                 752911 non-null  str
dtypes: float64(2), int64(5), str(13)
memory usage: 114.9 MB

In [4]:
df.columns

Index(['DR_NO', 'Date reported', 'Time reported', 'Date occurred',
       'Time occurred', 'AREA', 'AREA NAME', 'Report District No',
       'Crime Code', 'Crime Code  Description', 'Victim Age', 'Victim Gender',
       'Victim Descent', 'Premises Code', 'Premises Desc', 'Weapon Used Code',
       'Weapon Used Description', 'Status', 'Status Description', 'Location'],
      dtype='str')

In [7]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [7]:
df.columns

Index(['dr_no', 'date_reported', 'time_reported', 'date_occurred',
       'time_occurred', 'area', 'area_name', 'report_district_no',
       'crime_code', 'crime_code__description', 'victim_age', 'victim_gender',
       'victim_descent', 'premises_code', 'premises_desc', 'weapon_used_code',
       'weapon_used_description', 'status', 'status_description', 'location'],
      dtype='str')

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.isnull().sum()

dr_no                           0
date_reported                   0
time_reported                   0
date_occurred                   0
time_occurred                   0
area                            0
area_name                       0
report_district_no              0
crime_code                      0
crime_code__description         0
victim_age                      0
victim_gender               98230
victim_descent              98236
premises_code                   9
premises_desc                 435
weapon_used_code           491439
weapon_used_description    491439
status                          0
status_description              0
location                        0
dtype: int64

In [11]:
df['victim_gender'] = df['victim_gender'].fillna('Unknown')

In [12]:
df['victim_descent'] = df['victim_descent'].fillna('Unknown')

In [13]:
df['premises_desc'] = df['premises_desc'].fillna('Not Specified')

In [14]:
df['weapon_used_description'] = df['weapon_used_description'].fillna('No Weapon')

In [15]:
df['weapon_used_code'] = df['weapon_used_code'].fillna(0)

In [16]:
df.isnull().sum()

dr_no                      0
date_reported              0
time_reported              0
date_occurred              0
time_occurred              0
area                       0
area_name                  0
report_district_no         0
crime_code                 0
crime_code__description    0
victim_age                 0
victim_gender              0
victim_descent             0
premises_code              9
premises_desc              0
weapon_used_code           0
weapon_used_description    0
status                     0
status_description         0
location                   0
dtype: int64

In [17]:
df['victim_age'].describe()

count    752911.000000
mean         29.917438
std          21.730057
min          -2.000000
25%          11.000000
50%          31.000000
75%          45.000000
max         120.000000
Name: victim_age, dtype: float64

In [18]:
df = df[(df['victim_age'] > 0) & (df['victim_age'] < 100)]

In [19]:
df['victim_age'].describe()

count    569197.000000
mean         39.573501
std          15.570925
min           2.000000
25%          28.000000
50%          37.000000
75%          50.000000
max          99.000000
Name: victim_age, dtype: float64

In [20]:
df['date_reported'] = pd.to_datetime(df['date_reported'])
df['date_occurred'] = pd.to_datetime(df['date_occurred'])

In [21]:
df['year'] = df['date_occurred'].dt.year
df['month'] = df['date_occurred'].dt.month
df['day_name'] = df['date_occurred'].dt.day_name()

In [22]:
df['day_type'] = df['date_occurred'].dt.weekday

df['day_type'] = df['day_type'].apply(lambda x: "Weekend" if x>=5 else "Weekday")

In [23]:
df.shape

(569197, 24)

In [25]:
df.dtypes

dr_no                               int64
date_reported              datetime64[us]
time_reported                         str
date_occurred              datetime64[us]
time_occurred                         str
area                                int64
area_name                             str
report_district_no                  int64
crime_code                          int64
crime_code__description               str
victim_age                          int64
victim_gender                         str
victim_descent                        str
premises_code                     float64
premises_desc                         str
weapon_used_code                  float64
weapon_used_description               str
status                                str
status_description                    str
location                              str
year                                int32
month                               int32
day_name                              str
day_type                              str
dtype: object

In [29]:
df['premises_code'] = df['premises_code'].astype(int)
df['weapon_used_code'] = df['weapon_used_code'].astype(int)

In [30]:
df.head(20)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,...,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location,year,month,day_name,day_type
0,10304468,2020-01-08,8:42:40 AM,2020-01-08,7:01:35 PM,3,Southwest,377,624,Battery - Simple Assault,...,Single Family Dwelling,400,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,1100 W 39Th Pl,2020,1,Wednesday,Weekday
1,190101086,2020-01-02,3:08:56 PM,2020-01-01,9:07:23 AM,1,Central,163,624,Battery - Simple Assault,...,Sidewalk,500,Unknown Weapon/Other Weapon,IC,Invest Cont,700 S Hill St,2020,1,Wednesday,Weekday
3,191501505,2020-01-01,2:27:04 PM,2020-01-01,10:46:48 AM,15,N Hollywood,1543,745,Vandalism - Misdeameanor ($399 Or Under),...,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0,No Weapon,IC,Invest Cont,5400 Corteen Pl,2020,1,Wednesday,Weekday
4,191921269,2020-01-01,8:45:43 PM,2020-01-01,11:15:31 PM,19,Mission,1998,740,"Vandalism - Felony ($400 & Over, All Church Va...",...,Beauty Supply Store,0,No Weapon,IC,Invest Cont,14400 Titus St,2020,1,Wednesday,Weekday
5,200100501,2020-01-02,2:24:24 AM,2020-01-01,12:06:39 AM,1,Central,163,121,"Rape, Forcible",...,Night Club (Open Evenings Only),500,Unknown Weapon/Other Weapon,IC,Invest Cont,700 S Broadway,2020,1,Wednesday,Weekday
6,200100502,2020-01-02,9:08:23 AM,2020-01-02,6:59:02 PM,1,Central,161,442,Shoplifting - Petty Theft ($950 & Under),...,Department Store,0,No Weapon,IC,Invest Cont,700 S Figueroa St,2020,1,Thursday,Weekday
8,200100507,2020-01-04,3:24:54 AM,2020-01-04,7:46:07 AM,1,Central,101,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",...,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0,No Weapon,IC,Invest Cont,700 Bernard St,2020,1,Saturday,Weekend
10,200100509,2020-01-04,3:05:49 PM,2020-01-04,9:55:54 AM,1,Central,192,330,Burglary From Vehicle,...,Street,306,Rock/Thrown Object,IC,Invest Cont,15Th,2020,1,Saturday,Weekend
11,200100510,2020-01-05,3:41:46 PM,2020-01-05,10:18:31 PM,1,Central,111,930,Criminal Threats - No Weapon Displayed,...,Parking Lot,511,Verbal Threat,IC,Invest Cont,800 N Alameda St,2020,1,Sunday,Weekend
12,200100514,2020-01-05,9:49:23 PM,2020-01-05,2:02:18 AM,1,Central,162,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",...,Hotel,0,No Weapon,AA,Adult Arrest,800 S Olive St,2020,1,Sunday,Weekend
14,200100520,2020-01-08,8:27:16 AM,2020-01-08,8:47:27 PM,1,Central,128,442,Shoplifting - Petty Theft ($950 & Under),...,"Coffee Shop (Starbucks, Coffee Bean, Peet'S, E...",0,No Weapon,IC,Invest Cont,100 S Los Angeles St,2020,1,Wednesday,Weekday
15,211916029,2021-11-26,5:25:32 PM,2020-11-30,9:43:47 PM,19,Mission,1916,626,Intimate Partner - Simple Assault,...,Single Family Dwelling,400,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,14200 Berg St,2020,11,Monday,Weekday
16,201116159,2020-11-29,7:02:21 AM,2020-11-28,9:35:58 AM,11,Northeast,1124,626,Intimate Partner - Simple Assault,...,Single Family Dwelling,400,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,3200 W Avenue 32,2020,11,Saturday,Weekend
17,200506268,2020-02-22,11:39:56 PM,2020-02-22,5:40:19 AM,5,Harbor,511,440,Theft Plain - Petty ($950 & Under),...,Sidewalk,400,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,Pacific Coast,2020,2,Saturday,Weekend
18,210916801,2021-11-22,11:30:26 AM,2020-11-19,5:21:32 AM,9,Van Nuys,932,354,Theft Of Identity,...,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0,No Weapon,IC,Invest Cont,14700 Friar St,2020,11,Thursday,Weekday
19,200100535,2020-01-14,6:59:21 AM,2020-01-14,1:04:09 AM,1,Central,152,210,Robbery,...,Alley,204,Folding Knife,IC,Invest Cont,7Th,2020,1,Tuesday,Weekday
20,200914517,2020-09-10,8:31:37 AM,2020-09-09,8:25:32 AM,9,Van Nuys,909,354,Theft Of Identity,...,Condominium/Townhouse,0,No Weapon,IC,Invest Cont,13600 Leadwell St,2020,9,Wednesday,Weekday
21,200100538,2020-01-14,4:24:00 AM,2020-01-14,5:07:52 AM,1,Central,162,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",...,Department Store,0,No Weapon,IC,Invest Cont,700 W 7Th St,2020,1,Tuesday,Weekday
22,200100543,2020-01-15,1:00:16 PM,2020-01-15,4:28:15 PM,1,Central,162,442,Shoplifting - Petty Theft ($950 & Under),...,Department Store,0,No Weapon,IC,Invest Cont,700 W 7Th St,2020,1,Wednesday,Weekday
23,211014725,2021-11-18,11:48:38 PM,2020-12-28,12:14:07 PM,10,West Valley,1045,354,Theft Of Identity,...,Single Family Dwelling,0,No Weapon,IC,Invest Cont,5700 Enfield Av,2020,12,Monday,Weekday

In [8]:
df.tail(20)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,victim_age,victim_gender,victim_descent,premises_code,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location
752891,230112241,05-12-2023,12:35:20 PM,05-05-2023,5:20:08 PM,1,Central,142,210,Robbery,73,M,H,809.0,Metrolink Train,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,300 S Hill St
752892,230509679,06-07-2023,4:05:03 AM,06-07-2023,6:46:00 PM,5,Harbor,529,624,Battery - Simple Assault,63,M,H,108.0,Parking Lot,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,Anaheim St
752893,231300825,06-07-2023,6:08:41 PM,06-07-2023,1:26:24 PM,13,Newton,1322,624,Battery - Simple Assault,45,F,B,108.0,Parking Lot,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,2300 Wall St
752894,230908346,04-19-2023,9:43:03 PM,04-18-2023,7:07:09 PM,9,Van Nuys,969,354,Theft Of Identity,34,F,B,501.0,Single Family Dwelling,NaN,NaN,IC,Invest Cont,4800 Coldwater Canyon Av
752895,230406516,03-19-2023,8:51:40 AM,03-19-2023,8:52:22 PM,4,Hollenbeck,488,510,Vehicle - Stolen,0,NaN,NaN,101.0,Street,NaN,NaN,IC,Invest Cont,3200 Garnet St
752896,230609209,05-01-2023,9:55:46 PM,04-29-2023,11:17:28 AM,6,Hollywood,639,510,Vehicle - Stolen,0,NaN,NaN,101.0,Street,NaN,NaN,IC,Invest Cont,1800 Winona Bl
752897,230405171,02-05-2023,12:24:20 PM,02-02-2023,10:08:08 AM,4,Hollenbeck,428,236,Intimate Partner - Aggravated Assault,41,F,H,504.0,Other Residence,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,3000 Budau Av
752898,231007583,04-03-2023,12:50:08 AM,04-02-2023,10:29:43 PM,10,West Valley,1031,310,Burglary,37,M,W,501.0,Single Family Dwelling,NaN,NaN,IC,Invest Cont,19500 Victory Bl
752899,231405429,02-05-2023,12:15:16 PM,02-05-2023,1:02:33 AM,14,Pacific,1444,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",0,X,X,402.0,Market,NaN,NaN,IC,Invest Cont,4300 Lincoln Bl
752900,231710498,05-29-2023,3:32:31 PM,05-29-2023,10:16:57 PM,17,Devonshire,1701,626,Intimate Partner - Simple Assault,27,F,H,501.0,Single Family Dwelling,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,11400 Porter Ranch Dr
752901,230809415,05-10-2023,9:48:51 AM,05-10-2023,7:43:22 PM,8,West LA,859,888,Trespassing,57,F,H,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",NaN,NaN,IC,Invest Cont,8500 Horner St
752902,231609172,06-14-2023,8:37:53 AM,06-14-2023,9:43:39 AM,16,Foothill,1684,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",23,F,H,248.0,Cell Phone Store,NaN,NaN,IC,Invest Cont,8000 Webb Av
752903,230806871,03-03-2023,7:47:11 AM,03-02-2023,5:14:20 AM,8,West LA,889,354,Theft Of Identity,25,M,W,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",NaN,NaN,IC,Invest Cont,2000 S Holt Av
752904,231104474,01-12-2023,9:26:03 AM,01-12-2023,9:47:33 PM,11,Northeast,1107,440,Theft Plain - Petty ($950 & Under),42,M,W,101.0,Street,NaN,NaN,IC,Invest Cont,1000 Milwaukee Av
752905,230804266,01-08-2023,2:50:06 AM,01-08-2023,6:32:48 PM,8,West LA,839,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",48,M,O,717.0,Health Spa/Gym,NaN,NaN,IC,Invest Cont,10200 Santa Monica Bl
752906,231510379,05-29-2023,3:29:47 AM,05-25-2023,5:20:25 AM,15,N Hollywood,1548,662,"Bunco, Grand Theft",25,M,W,710.0,Other Premise,NaN,NaN,IC,Invest Cont,5300 Denny Av
752907,231604807,01-27-2023,6:57:52 AM,01-26-2023,1:33:08 PM,16,Foothill,1663,740,"Vandalism - Felony ($400 & Over, All Church Va...",23,M,H,122.0,"Vehicle, Passenger/Truck",NaN,NaN,IC,Invest Cont,12500 Branford St
752908,231606525,03-22-2023,1:38:26 PM,03-22-2023,11:29:55 PM,16,Foothill,1602,230,"Assault With Deadly Weapon, Aggravated Assault",25,F,H,102.0,Sidewalk,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,12800 Filmore St
752909,231210064,04-12-2023,9:12:40 AM,04-12-2023,10:43:14 PM,12,77th Street,1239,230,"Assault With Deadly Weapon, Aggravated Assault",29,M,B,222.0,Laundromat,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,6100 S Vermont Av
752910,230906458,03-05-2023,12:32:33 AM,03-05-2023,11:00:54 AM,9,Van Nuys,914,745,Vandalism - Misdeameanor ($399 Or Under),53,F,H,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",NaN,NaN,IC,Invest Cont,14500 Hartland St

In [9]:
df['location'].head(20)

0           1100 W 39Th Pl
1            700 S Hill St
2             200 E 6Th St
3          5400 Corteen Pl
4           14400 Titus St
5           700 S Broadway
6        700 S Figueroa St
7             200 E 6Th St
8           700 Bernard St
9          11900 Balboa Bl
10                    15Th
11        800 N Alameda St
12          800 S Olive St
13            700 W 7Th St
14    100 S Los Angeles St
15           14200 Berg St
16        3200 W Avenue 32
17           Pacific Coast
18          14700 Friar St
19                     7Th
Name: location, dtype: str

In [10]:
df['location'].value_counts().head(10)

location
800 N Alameda St         1389
7Th                      1239
6Th St                   1235
7Th St                   1199
6Th                      1158
10200 Santa Monica Bl    1149
100 The Grove Dr         1009
Figueroa St               984
5Th                       976
Broadway                  942
Name: count, dtype: int64

In [11]:
df['location'] = df['location'].str.strip()

In [12]:
df['location'] = df['location'].str.title()

In [13]:
df['location'].value_counts().head(20)

location
800 N Alameda St          1389
7Th                       1239
6Th St                    1235
7Th St                    1199
6Th                       1158
10200 Santa Monica Bl     1149
100 The Grove Dr          1009
Figueroa St                984
5Th                        976
Broadway                   942
Hollywood                  933
Vermont Av                 931
Western Av                 877
700 S Figueroa St          864
9300 Tampa Av              838
8Th St                     822
3Rd St                     802
6600 Topanga Canyon Bl     767
Sunset                     743
Wilshire                   729
Name: count, dtype: int64

In [10]:
df.loc[df['victim_age'] == 0, 'victim_age'] = None

KeyError: 'victim_age'

In [7]:
df['victim_gender'] = df['victim_gender'].fillna('Unknown')
df['victim_descent'] = df['victim_descent'].fillna('Unknown')

KeyError: 'victim_gender'

In [16]:
df['weapon_used_description'] = df['weapon_used_description'].fillna('No Weapon')
df['weapon_used_code'] = df['weapon_used_code'].fillna(0)

In [17]:
df.head(5)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,victim_age,victim_gender,victim_descent,premises_code,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location
0,10304468,01-08-2020,8:42:40 AM,01-08-2020,7:01:35 PM,3,Southwest,377,624,Battery - Simple Assault,36.0,F,B,501.0,Single Family Dwelling,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,1100 W 39Th Pl
1,190101086,01-02-2020,3:08:56 PM,01-01-2020,9:07:23 AM,1,Central,163,624,Battery - Simple Assault,25.0,M,H,102.0,Sidewalk,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,700 S Hill St
2,200110444,04-14-2020,2:53:31 PM,02-13-2020,7:53:55 AM,1,Central,155,845,Sex Offender Registrant Out Of Compliance,NaN,X,X,726.0,Police Facility,0.0,No Weapon,AA,Adult Arrest,200 E 6Th St
3,191501505,01-01-2020,2:27:04 PM,01-01-2020,10:46:48 AM,15,N Hollywood,1543,745,Vandalism - Misdeameanor ($399 Or Under),76.0,F,W,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,5400 Corteen Pl
4,191921269,01-01-2020,8:45:43 PM,01-01-2020,11:15:31 PM,19,Mission,1998,740,"Vandalism - Felony ($400 & Over, All Church Va...",31.0,X,X,409.0,Beauty Supply Store,0.0,No Weapon,IC,Invest Cont,14400 Titus St

In [18]:
df.tail(10)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,victim_age,victim_gender,victim_descent,premises_code,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location
752901,230809415,05-10-2023,9:48:51 AM,05-10-2023,7:43:22 PM,8,West LA,859,888,Trespassing,57.0,F,H,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,8500 Horner St
752902,231609172,06-14-2023,8:37:53 AM,06-14-2023,9:43:39 AM,16,Foothill,1684,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",23.0,F,H,248.0,Cell Phone Store,0.0,No Weapon,IC,Invest Cont,8000 Webb Av
752903,230806871,03-03-2023,7:47:11 AM,03-02-2023,5:14:20 AM,8,West LA,889,354,Theft Of Identity,25.0,M,W,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,2000 S Holt Av
752904,231104474,01-12-2023,9:26:03 AM,01-12-2023,9:47:33 PM,11,Northeast,1107,440,Theft Plain - Petty ($950 & Under),42.0,M,W,101.0,Street,0.0,No Weapon,IC,Invest Cont,1000 Milwaukee Av
752905,230804266,01-08-2023,2:50:06 AM,01-08-2023,6:32:48 PM,8,West LA,839,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",48.0,M,O,717.0,Health Spa/Gym,0.0,No Weapon,IC,Invest Cont,10200 Santa Monica Bl
752906,231510379,05-29-2023,3:29:47 AM,05-25-2023,5:20:25 AM,15,N Hollywood,1548,662,"Bunco, Grand Theft",25.0,M,W,710.0,Other Premise,0.0,No Weapon,IC,Invest Cont,5300 Denny Av
752907,231604807,01-27-2023,6:57:52 AM,01-26-2023,1:33:08 PM,16,Foothill,1663,740,"Vandalism - Felony ($400 & Over, All Church Va...",23.0,M,H,122.0,"Vehicle, Passenger/Truck",0.0,No Weapon,IC,Invest Cont,12500 Branford St
752908,231606525,03-22-2023,1:38:26 PM,03-22-2023,11:29:55 PM,16,Foothill,1602,230,"Assault With Deadly Weapon, Aggravated Assault",25.0,F,H,102.0,Sidewalk,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,12800 Filmore St
752909,231210064,04-12-2023,9:12:40 AM,04-12-2023,10:43:14 PM,12,77th Street,1239,230,"Assault With Deadly Weapon, Aggravated Assault",29.0,M,B,222.0,Laundromat,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,6100 S Vermont Av
752910,230906458,03-05-2023,12:32:33 AM,03-05-2023,11:00:54 AM,9,Van Nuys,914,745,Vandalism - Misdeameanor ($399 Or Under),53.0,F,H,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,14500 Hartland St

In [19]:
df.tail(20)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,victim_age,victim_gender,victim_descent,premises_code,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location
752891,230112241,05-12-2023,12:35:20 PM,05-05-2023,5:20:08 PM,1,Central,142,210,Robbery,73.0,M,H,809.0,Metrolink Train,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,300 S Hill St
752892,230509679,06-07-2023,4:05:03 AM,06-07-2023,6:46:00 PM,5,Harbor,529,624,Battery - Simple Assault,63.0,M,H,108.0,Parking Lot,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,Anaheim St
752893,231300825,06-07-2023,6:08:41 PM,06-07-2023,1:26:24 PM,13,Newton,1322,624,Battery - Simple Assault,45.0,F,B,108.0,Parking Lot,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,2300 Wall St
752894,230908346,04-19-2023,9:43:03 PM,04-18-2023,7:07:09 PM,9,Van Nuys,969,354,Theft Of Identity,34.0,F,B,501.0,Single Family Dwelling,0.0,No Weapon,IC,Invest Cont,4800 Coldwater Canyon Av
752895,230406516,03-19-2023,8:51:40 AM,03-19-2023,8:52:22 PM,4,Hollenbeck,488,510,Vehicle - Stolen,NaN,Unknown,Unknown,101.0,Street,0.0,No Weapon,IC,Invest Cont,3200 Garnet St
752896,230609209,05-01-2023,9:55:46 PM,04-29-2023,11:17:28 AM,6,Hollywood,639,510,Vehicle - Stolen,NaN,Unknown,Unknown,101.0,Street,0.0,No Weapon,IC,Invest Cont,1800 Winona Bl
752897,230405171,02-05-2023,12:24:20 PM,02-02-2023,10:08:08 AM,4,Hollenbeck,428,236,Intimate Partner - Aggravated Assault,41.0,F,H,504.0,Other Residence,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,3000 Budau Av
752898,231007583,04-03-2023,12:50:08 AM,04-02-2023,10:29:43 PM,10,West Valley,1031,310,Burglary,37.0,M,W,501.0,Single Family Dwelling,0.0,No Weapon,IC,Invest Cont,19500 Victory Bl
752899,231405429,02-05-2023,12:15:16 PM,02-05-2023,1:02:33 AM,14,Pacific,1444,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",NaN,X,X,402.0,Market,0.0,No Weapon,IC,Invest Cont,4300 Lincoln Bl
752900,231710498,05-29-2023,3:32:31 PM,05-29-2023,10:16:57 PM,17,Devonshire,1701,626,Intimate Partner - Simple Assault,27.0,F,H,501.0,Single Family Dwelling,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,11400 Porter Ranch Dr
752901,230809415,05-10-2023,9:48:51 AM,05-10-2023,7:43:22 PM,8,West LA,859,888,Trespassing,57.0,F,H,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,8500 Horner St
752902,231609172,06-14-2023,8:37:53 AM,06-14-2023,9:43:39 AM,16,Foothill,1684,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",23.0,F,H,248.0,Cell Phone Store,0.0,No Weapon,IC,Invest Cont,8000 Webb Av
752903,230806871,03-03-2023,7:47:11 AM,03-02-2023,5:14:20 AM,8,West LA,889,354,Theft Of Identity,25.0,M,W,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,2000 S Holt Av
752904,231104474,01-12-2023,9:26:03 AM,01-12-2023,9:47:33 PM,11,Northeast,1107,440,Theft Plain - Petty ($950 & Under),42.0,M,W,101.0,Street,0.0,No Weapon,IC,Invest Cont,1000 Milwaukee Av
752905,230804266,01-08-2023,2:50:06 AM,01-08-2023,6:32:48 PM,8,West LA,839,341,"Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Li...",48.0,M,O,717.0,Health Spa/Gym,0.0,No Weapon,IC,Invest Cont,10200 Santa Monica Bl
752906,231510379,05-29-2023,3:29:47 AM,05-25-2023,5:20:25 AM,15,N Hollywood,1548,662,"Bunco, Grand Theft",25.0,M,W,710.0,Other Premise,0.0,No Weapon,IC,Invest Cont,5300 Denny Av
752907,231604807,01-27-2023,6:57:52 AM,01-26-2023,1:33:08 PM,16,Foothill,1663,740,"Vandalism - Felony ($400 & Over, All Church Va...",23.0,M,H,122.0,"Vehicle, Passenger/Truck",0.0,No Weapon,IC,Invest Cont,12500 Branford St
752908,231606525,03-22-2023,1:38:26 PM,03-22-2023,11:29:55 PM,16,Foothill,1602,230,"Assault With Deadly Weapon, Aggravated Assault",25.0,F,H,102.0,Sidewalk,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,12800 Filmore St
752909,231210064,04-12-2023,9:12:40 AM,04-12-2023,10:43:14 PM,12,77th Street,1239,230,"Assault With Deadly Weapon, Aggravated Assault",29.0,M,B,222.0,Laundromat,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,6100 S Vermont Av
752910,230906458,03-05-2023,12:32:33 AM,03-05-2023,11:00:54 AM,9,Van Nuys,914,745,Vandalism - Misdeameanor ($399 Or Under),53.0,F,H,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,14500 Hartland St

In [20]:
df['crime_code__description'].unique()

<StringArray>
[                                'Battery - Simple Assault',
                'Sex Offender Registrant Out Of Compliance',
                 'Vandalism - Misdeameanor ($399 Or Under)',
  'Vandalism - Felony ($400 & Over, All Church Vandalisms)',
                                           'Rape, Forcible',
                 'Shoplifting - Petty Theft ($950 & Under)',
                                'Other Miscellaneous Crime',
 'Theft-Grand ($950.01 & Over)Excpt,Guns,Fowl,Livestk,Prod',
                                    'Burglary From Vehicle',
                   'Criminal Threats - No Weapon Displayed',
 ...
                                        'Child Abandonment',
                              'Telephone Property - Damage',
 'Beastiality, Crime Against Nature Sexual Asslt With Anim',
                                                   'Bigamy',
                                      'Failure To Disperse',
       'Firearms Emergency Protective Order (Firearms Epo)',
             'Incest (Sexual Acts Between Blood Relatives)',
                       'Dishonest Employee Attempted Theft',
                           'Blocking Door Induction Center',
                                          'Inciting A Riot']
Length: 138, dtype: str

In [21]:
def categorize_crime(x):
    x = x.lower()
    
    if 'theft' in x or 'shoplifting' in x:
        return 'Theft'
    
    elif 'assault' in x or 'battery' in x:
        return 'Assault'
    
    elif 'burglary' in x:
        return 'Burglary'
    
    elif 'vandalism' in x:
        return 'Vandalism'
    
    elif 'rape' in x or 'sex' in x:
        return 'Sexual Crime'
    
    elif 'vehicle' in x:
        return 'Vehicle Crime'
    
    else:
        return 'Other'

df['crime_category'] = df['crime_code__description'].apply(categorize_crime)

In [23]:
df.head(5)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,...,victim_gender,victim_descent,premises_code,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location,crime_category
0,10304468,01-08-2020,8:42:40 AM,01-08-2020,7:01:35 PM,3,Southwest,377,624,Battery - Simple Assault,...,F,B,501.0,Single Family Dwelling,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,1100 W 39Th Pl,Assault
1,190101086,01-02-2020,3:08:56 PM,01-01-2020,9:07:23 AM,1,Central,163,624,Battery - Simple Assault,...,M,H,102.0,Sidewalk,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,700 S Hill St,Assault
2,200110444,04-14-2020,2:53:31 PM,02-13-2020,7:53:55 AM,1,Central,155,845,Sex Offender Registrant Out Of Compliance,...,X,X,726.0,Police Facility,0.0,No Weapon,AA,Adult Arrest,200 E 6Th St,Sexual Crime
3,191501505,01-01-2020,2:27:04 PM,01-01-2020,10:46:48 AM,15,N Hollywood,1543,745,Vandalism - Misdeameanor ($399 Or Under),...,F,W,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,5400 Corteen Pl,Vandalism
4,191921269,01-01-2020,8:45:43 PM,01-01-2020,11:15:31 PM,19,Mission,1998,740,"Vandalism - Felony ($400 & Over, All Church Va...",...,X,X,409.0,Beauty Supply Store,0.0,No Weapon,IC,Invest Cont,14400 Titus St,Vandalism

In [24]:
df['location'] = df['location'].str.title().str.strip()

In [26]:
df['age_group'] = pd.cut(
    df['victim_age'],
    bins=[0,18,30,45,60,100],
    labels=['0-18','19-30','31-45','46-60','60+']
)

In [27]:
df['premises_desc'] = df['premises_desc'].str.title().str.strip()

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df['crime_hour'] = pd.to_datetime(df['time_occurred'], errors='coerce').dt.hour

In [36]:
df.loc[df['victim_age']==0,'victim_age']=None

In [37]:
(df['date_reported'] < df['date_occurred']).sum()

np.int64(14031)

In [38]:
df = df[df['date_reported'] >= df['date_occurred']]

In [39]:
df.shape

(738880, 23)

In [40]:
(df['date_reported'] < df['date_occurred']).sum()

np.int64(0)

In [41]:
df.sample(10)

,dr_no,date_reported,time_reported,date_occurred,time_occurred,area,area_name,report_district_no,crime_code,crime_code__description,...,premises_code,premises_desc,weapon_used_code,weapon_used_description,status,status_description,location,crime_category,age_group,crime_hour
709577,231707664,04-02-2023,08:50:30,04-01-2023,21:36:48,17,Devonshire,1785,310,Burglary,...,203.0,Other Business,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,8700 Reseda Bl,Burglary,NaN,NaN
268600,212006001,02-24-2021,10:36:39,02-24-2021,22:54:02,20,Olympic,2026,480,Bike - Stolen,...,210.0,Restaurant/Fast Food,0.0,No Weapon,IC,Invest Cont,300 S Vermont Av,Other,0-18,NaN
502158,221015161,10-12-2022,10:17:04,10-11-2022,12:55:39,10,West Valley,1078,310,Burglary,...,501.0,Single Family Dwelling,500.0,Unknown Weapon/Other Weapon,IC,Invest Cont,16100 Hartsook St,Burglary,31-45,NaN
228922,211222710,11-03-2021,05:12:08,11-02-2021,20:57:06,12,77th Street,1208,236,Intimate Partner - Aggravated Assault,...,101.0,Street,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,4600 S Figueroa St,Assault,19-30,NaN
367581,210706064,02-24-2021,22:39:59,02-24-2021,06:19:20,7,Wilshire,725,900,Violation Of Court Order,...,501.0,Single Family Dwelling,0.0,No Weapon,IC,Invest Cont,5900 W 3Rd St,Other,31-45,NaN
626254,220117838,08-08-2022,11:31:14,08-08-2022,00:16:28,1,Central,192,624,Battery - Simple Assault,...,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",AO,Adult Other,1300 S Flower St,Assault,31-45,NaN
155296,201208069,02-28-2020,19:01:31,02-28-2020,05:36:41,12,77th Street,1207,624,Battery - Simple Assault,...,501.0,Single Family Dwelling,400.0,"Strong-Arm (Hands, Fist, Feet Or Bodily Force)",IC,Invest Cont,800 W 50Th Pl,Assault,0-18,NaN
626244,220217123,09-20-2022,08:30:33,09-03-2022,10:18:00,2,Rampart,233,354,Theft Of Identity,...,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,200 S Occidental Bl,Theft,19-30,NaN
354103,211214548,06-25-2021,19:41:05,06-24-2021,16:32:18,12,77th Street,1233,420,Theft From Motor Vehicle - Petty ($950 & Under),...,108.0,Parking Lot,0.0,No Weapon,IC,Invest Cont,1800 W Slauson Av,Theft,46-60,NaN
650628,230905046,01-30-2023,01:14:49,01-27-2023,16:06:22,9,Van Nuys,971,354,Theft Of Identity,...,502.0,"Multi-Unit Dwelling (Apartment, Duplex, Etc)",0.0,No Weapon,IC,Invest Cont,4700 Kester Av,Theft,31-45,NaN

In [46]:
df['crime_hour'] = pd.to_datetime(df['time_occurred'], errors='coerce').dt.hour

In [47]:
df[['time_occurred','crime_hour']].head()

  time_occurred  crime_hour
0      19:01:35         NaN
1      09:07:23         NaN
2      07:53:55         NaN
3      10:46:48         NaN
4      23:15:31         NaN

In [65]:
df.to_csv("cleaned_crime_dataset.csv", index=False)
print('saved successfully')

saved successfully

In [55]:
df.isnull().sum()

DR_NO                           0
Date reported                   0
Time reported                   0
Date occurred                   0
Time occurred                   0
AREA                            0
AREA NAME                       0
Report District No              0
Crime Code                      0
Crime Code  Description         0
Victim Age                      0
Victim Gender               98230
Victim Descent              98236
Premises Code                   9
Premises Desc                 435
Weapon Used Code           491439
Weapon Used Description    491439
Status                          0
Status Description              0
Location                        0
dtype: int64

In [58]:
df.isnull().sum()

DR_NO                           0
Date reported                   0
Time reported                   0
Date occurred                   0
Time occurred                   0
AREA                            0
AREA NAME                       0
Report District No              0
Crime Code                      0
Crime Code  Description         0
Victim Age                      0
Victim Gender                   0
Victim Descent                  0
Premises Code                   9
Premises Desc                 435
Weapon Used Code           491439
Weapon Used Description    491439
Status                          0
Status Description              0
Location                        0
dtype: int64

In [60]:
df['Premises Desc'] = df['Premises Desc'].fillna('Unknown')
df['Premises Code'] = df['Premises Code'].fillna(0)

In [61]:
df.isnull().sum()

DR_NO                           0
Date reported                   0
Time reported                   0
Date occurred                   0
Time occurred                   0
AREA                            0
AREA NAME                       0
Report District No              0
Crime Code                      0
Crime Code  Description         0
Victim Age                      0
Victim Gender                   0
Victim Descent                  0
Premises Code                   0
Premises Desc                   0
Weapon Used Code           491439
Weapon Used Description    491439
Status                          0
Status Description              0
Location                        0
dtype: int64

In [4]:
df['Weapon Used Description'] = df['Weapon Used Description'].fillna('No Weapon')
df['Weapon Used Code'] = df['Weapon Used Code'].fillna(0)

In [5]:
df.isnull().sum()

DR_NO                          0
Date reported                  0
Time reported                  0
Date occurred                  0
Time occurred                  0
AREA                           0
AREA NAME                      0
Report District No             0
Crime Code                     0
Crime Code  Description        0
Victim Age                     0
Victim Gender              98230
Victim Descent             98236
Premises Code                  9
Premises Desc                435
Weapon Used Code               0
Weapon Used Description        0
Status                         0
Status Description             0
Location                       0
dtype: int64

In [11]:
df['Victim Gender'] = df['Victim Gender'].fillna('Unknown')

In [12]:
df['Victim Descent'] = df['Victim Descent'].fillna('Unknown')

In [13]:
df['Premises Code'] = df['Premises Code'].fillna(0)

In [14]:
df['Premises Desc'] = df['Premises Desc'].fillna('Unknown')

In [15]:
df.isnull().sum()

DR_NO                           0
Date reported                   0
Time reported                   0
Date occurred                   0
Time occurred                   0
AREA                            0
AREA NAME                       0
Report District No              0
Crime Code                      0
Crime Code  Description         0
Victim Age                      0
Victim Gender                   0
Victim Descent                  0
Premises Code                   0
Premises Desc                   0
Weapon Used Code           491439
Weapon Used Description    491439
Status                          0
Status Description              0
Location                        0
dtype: int64

In [16]:
df.columns

Index(['DR_NO', 'Date reported', 'Time reported', 'Date occurred',
       'Time occurred', 'AREA', 'AREA NAME', 'Report District No',
       'Crime Code', 'Crime Code  Description', 'Victim Age', 'Victim Gender',
       'Victim Descent', 'Premises Code', 'Premises Desc', 'Weapon Used Code',
       'Weapon Used Description', 'Status', 'Status Description', 'Location'],
      dtype='str')

In [17]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [18]:
df.columns

Index(['dr_no', 'date_reported', 'time_reported', 'date_occurred',
       'time_occurred', 'area', 'area_name', 'report_district_no',
       'crime_code', 'crime_code__description', 'victim_age', 'victim_gender',
       'victim_descent', 'premises_code', 'premises_desc', 'weapon_used_code',
       'weapon_used_description', 'status', 'status_description', 'location'],
      dtype='str')

In [19]:
df['victim_gender'] = df['victim_gender'].fillna('Unknown')

df['victim_descent'] = df['victim_descent'].fillna('Unknown')

df['premises_code'] = df['premises_code'].fillna(0)

df['premises_desc'] = df['premises_desc'].fillna('Unknown')

In [20]:
df.isnull().sum()

dr_no                           0
date_reported                   0
time_reported                   0
date_occurred                   0
time_occurred                   0
area                            0
area_name                       0
report_district_no              0
crime_code                      0
crime_code__description         0
victim_age                      0
victim_gender                   0
victim_descent                  0
premises_code                   0
premises_desc                   0
weapon_used_code           491439
weapon_used_description    491439
status                          0
status_description              0
location                        0
dtype: int64

In [21]:
df['weapon_used_description'] = df['weapon_used_description'].fillna('No Weapon')

df['weapon_used_code'] = df['weapon_used_code'].fillna(0)

In [22]:
df.isnull().sum()

dr_no                      0
date_reported              0
time_reported              0
date_occurred              0
time_occurred              0
area                       0
area_name                  0
report_district_no         0
crime_code                 0
crime_code__description    0
victim_age                 0
victim_gender              0
victim_descent             0
premises_code              0
premises_desc              0
weapon_used_code           0
weapon_used_description    0
status                     0
status_description         0
location                   0
dtype: int64

In [23]:
# rename columns
df.columns = df.columns.str.lower().str.replace(" ", "_")

# handle null values
df['victim_gender'] = df['victim_gender'].fillna('Unknown')
df['victim_descent'] = df['victim_descent'].fillna('Unknown')
df['premises_code'] = df['premises_code'].fillna(0)
df['premises_desc'] = df['premises_desc'].fillna('Unknown')
df['weapon_used_description'] = df['weapon_used_description'].fillna('No Weapon')
df['weapon_used_code'] = df['weapon_used_code'].fillna(0)

# verify
print(df.isnull().sum())

# save cleaned dataset
# df.to_csv("crime_cleaned_dataset.csv", index=False)

dr_no                      0
date_reported              0
time_reported              0
date_occurred              0
time_occurred              0
area                       0
area_name                  0
report_district_no         0
crime_code                 0
crime_code__description    0
victim_age                 0
victim_gender              0
victim_descent             0
premises_code              0
premises_desc              0
weapon_used_code           0
weapon_used_description    0
status                     0
status_description         0
location                   0
dtype: int64

In [24]:
df.to_csv("crime.csv", index=False)

In [25]:
df['victim_gender'] = df['victim_gender'].replace({
'M': 'Male',
'F': 'Female',
'X': 'Unknown'
})

In [26]:
df.loc[df['victim_age'] == 0, 'victim_age'] = None

In [27]:
df.to_csv("crime_final.csv", index=False)